name: tests-orders

on:
 pull_request:
    path:
      - 'orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@2
      - run: cd orders && npm install && npm run test:ci
    
